name: worldbar
version: '${project.version}'
main: com.gligoth.worldbar.Worldbar
api-version: '1.20'
commands:
  worldbar:
    description: Worldbar commands
  worldname:
    description: Easily see which world you are in
